const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=__dirname,DB=path.join(ROOT,'data','db.json'),PUBLIC=path.join(ROOT,'public');
const IS_VERCEL=!!process.env.VERCEL;
const MEMORY_KEY='__ISC_OFFICE_DB__';
const OFFICE={lat:13.3825321,lon:79.2684575,radiusM:250,source:'ISC office attendance permit · 500m diameter'};
const now=()=>new Date(),iso=()=>now().toISOString(),today=()=>iso().slice(0,10),id=p=>p+'_'+crypto.randomBytes(6).toString('hex');
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
function fresh(){return{settings:{adminWallet:0,dailyDefault:50,attendance:OFFICE,proximity:{enabled:true,radiusM:50,staleMs:10000}},proximity:{admin:null,teams:{}},users:[{id:'admin',username:'iscadmin',password:'8125400721',name:'ISC Administrator',role:'admin',active:true,dailyPay:0,wallet:0,upi:'',phone:'',photo:null,createdAt:iso()}],attendance:[],videos:[],meetings:[],meetingSignals:[],vouchers:[],withdrawals:[],transactions:[],notifications:[],notificationHistory:[],activity:[],smsLog:[]}}
function load(){
  if(IS_VERCEL && globalThis[MEMORY_KEY]) return globalThis[MEMORY_KEY];
  try{const d=JSON.parse(fs.readFileSync(DB,'utf8')),f=fresh();for(const k of Object.keys(f))if(d[k]===undefined)d[k]=f[k];d.settings={...f.settings,...(d.settings||{}),attendance:{...OFFICE,...((d.settings||{}).attendance||{})}};d.settings.dailyDefault=50;d.settings.adminWallet=Number(d.settings.adminWallet||0);d.settings.attendance={...OFFICE};d.settings.proximity={enabled:true,radiusM:50,staleMs:10000,...(d.settings.proximity||{})};d.proximity=d.proximity||{admin:null,teams:{}};d.proximity.teams=d.proximity.teams||{};for(const u of d.users){if(u.role==='member')u.dailyPay=50;if(u.role==='admin'){u.username='iscadmin';u.password='8125400721';}}
    if(IS_VERCEL) globalThis[MEMORY_KEY]=d;
    return d;
  }catch(e){
    const d=fresh();
    if(IS_VERCEL) globalThis[MEMORY_KEY]=d;
    return d;
  }
}
function save(d){
  if(IS_VERCEL){ globalThis[MEMORY_KEY]=d; return; }
  fs.mkdirSync(path.dirname(DB),{recursive:true});
  fs.writeFileSync(DB,JSON.stringify(d,null,2));
}
function safeUser(u){const{password,...x}=u;return x}
function send(res,status,obj){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(obj))}
function html(res,file){const f=path.join(PUBLIC,file);if(!fs.existsSync(f))return send(res,404,{error:'Not found'});const ext=path.extname(f),ct={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'}[ext]||'application/octet-stream';res.writeHead(200,{'Content-Type':ct,'Cache-Control':'no-store'});res.end(fs.readFileSync(f))}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>20e6)req.destroy()});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){reject(e)}});req.on('error',reject)})}
function cleanup(d){const cutoff=Date.now()-86400000;d.notifications=d.notifications.filter(n=>new Date(n.createdAt).getTime()>=cutoff)}
function note(d,userId,title,message,type='info'){const n={id:id('n'),userId,title,message,type,read:false,createdAt:iso()};d.notifications.unshift(n);d.notificationHistory.unshift({...n})}
function act(d,userId,action,detail){d.activity.unshift({id:id('a'),userId,action,detail,createdAt:iso()})}
function tx(d,ownerId,type,amount,description,meta={}){d.transactions.unshift({id:id('tx'),ownerId,type,amount:Number(amount),description,meta,createdAt:iso()})}
function period5(){const n=now(),y=n.getFullYear(),m=n.getMonth(),day=n.getDate();let start=new Date(y,m,5),end=new Date(y,m+1,5);if(day<5){start=new Date(y,m-1,5);end=new Date(y,m,5)}return{start:start.toISOString(),end:end.toISOString(),label:start.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})+' → '+end.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}}
function inRange(t,s,e){const x=new Date(t).getTime();return x>=new Date(s).getTime()&&x<new Date(e).getTime()}
function earningsFor(d,uid){const p=period5(),ts=d.transactions.filter(t=>t.ownerId===uid&&t.type==='EARNING'&&inRange(t.createdAt,p.start,p.end));return{period:p,total:ts.reduce((a,t)=>a+Number(t.amount),0),transactions:ts}}
function distanceM(lat1,lon1,lat2,lon2){const R=6371000,r=x=>x*Math.PI/180,dLat=r(lat2-lat1),dLon=r(lon2-lon1),a=Math.sin(dLat/2)**2+Math.cos(r(lat1))*Math.cos(r(lat2))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(a))}
async function sms(d,userId,message){const u=d.users.find(x=>x.id===userId);if(!u||!u.phone)return;const rec={id:id('sms'),userId,to:u.phone,message,status:'queued_no_provider',createdAt:iso()};d.smsLog.unshift(rec);if(process.env.SMS_PROVIDER==='twilio'&&process.env.TWILIO_ACCOUNT_SID&&process.env.TWILIO_AUTH_TOKEN&&process.env.TWILIO_FROM){try{const auth=Buffer.from(process.env.TWILIO_ACCOUNT_SID+':'+process.env.TWILIO_AUTH_TOKEN).toString('base64');const params=new URLSearchParams({To:u.phone,From:process.env.TWILIO_FROM,Body:message});const r=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${process.env.TWILIO_ACCOUNT_SID}/Messages.json`,{method:'POST',headers:{Authorization:'Basic '+auth,'Content-Type':'application/x-www-form-urlencoded'},body:params});rec.status=r.ok?'sent':'failed'}catch(e){rec.status='failed'}}}
function meetingFor(d,mid){return d.meetings.find(m=>m.id===mid)}
function meetingMember(d,m,uid){return !!m && (uid==='admin'||m.memberIds.includes(uid))}
function meetingSignal(d,meetingId,from,to,type,payload){const arr=d.meetingSignals||(d.meetingSignals=[]);arr.push({id:id('sig'),meetingId,from,to:to||null,type,payload,createdAt:Date.now()});if(arr.length>10000)d.meetingSignals=arr.slice(-10000)}
function settleRechargeFromAdmin(d,member,v){const amt=Number(v.amount);if(Number(d.settings.adminWallet)<amt)return false;d.settings.adminWallet-=amt;member.wallet=Number(member.wallet||0)+amt;tx(d,'admin','RECHARGE_FUND',-amt,'Admin wallet funded recharge escrow',{voucherId:v.id,memberId:member.id});tx(d,member.id,'RECHARGE_ESCROW',amt,'Recharge amount credited to team wallet',{voucherId:v.id,source:'admin_wallet'});member.wallet-=amt;d.settings.adminWallet+=amt;v.status='Paid';v.paidAt=iso();tx(d,member.id,'RECHARGE',-amt,'Recharge settled from team wallet to Admin',{voucherId:v.id,operator:v.operator,number:v.number});tx(d,'admin','RECHARGE_COLLECTION',amt,'Recharge amount returned to Admin wallet',{voucherId:v.id,memberId:member.id,operator:v.operator,number:v.number});note(d,member.id,'Recharge processed','₹'+amt+' recharge processed through the team wallet and returned to Admin for recharge settlement.','success');return true}
function processPendingRecharges(d){for(const v of d.vouchers){if(v.status!=='Pending')continue;const member=d.users.find(x=>x.id===v.userId);if(member)settleRechargeFromAdmin(d,member,v)}}
async function api(req,res){const d=load();cleanup(d);const u=new URL(req.url,'http://localhost'),p=u.pathname;
if(req.method==='POST'&&p==='/api/login'){const b=await body(req),x=d.users.find(x=>x.username===b.username&&x.password===b.password&&x.active!==false);if(!x)return send(res,401,{error:'Invalid login details'});act(d,x.id,'LOGIN','Signed in');save(d);return send(res,200,{user:safeUser(x),deviceSession:true})}
if(req.method==='GET'&&p==='/api/state'){const uid=u.searchParams.get('userId'),x=d.users.find(x=>x.id===uid);if(!x)return send(res,401,{error:'Session expired'});const out={user:safeUser(x),settings:d.settings,office:OFFICE,period:period5(),notifications:d.notifications.filter(n=>!n.userId||n.userId===uid),notificationHistory:d.notificationHistory.filter(n=>!n.userId||n.userId===uid),activity:d.activity};if(x.role==='admin'){out.users=d.users.map(safeUser);out.attendance=d.attendance;out.videos=d.videos;out.meetings=d.meetings;out.meetingSignals=undefined;out.vouchers=d.vouchers;out.withdrawals=d.withdrawals;out.transactions=d.transactions;out.smsLog=d.smsLog;out.adminEarnings=d.transactions.filter(t=>t.ownerId==='admin')}else{out.attendance=d.attendance.filter(a=>a.userId===uid);out.videos=d.videos.filter(v=>v.memberIds.includes(uid));out.meetings=d.meetings.filter(m=>m.memberIds.includes(uid));out.vouchers=d.vouchers.filter(v=>v.userId===uid);out.withdrawals=d.withdrawals.filter(w=>w.userId===uid);out.transactions=d.transactions.filter(t=>t.ownerId===uid);out.earnings=earningsFor(d,uid)}save(d);return send(res,200,out)}
if(req.method==='POST'&&p==='/api/team'){const b=await body(req);if(!b.name||!b.username||!b.password)return send(res,400,{error:'Name, User ID and password are required'});if(d.users.some(x=>x.username===b.username))return send(res,409,{error:'User ID already exists'});const x={id:id('u'),username:b.username,password:b.password,name:b.name,role:'member',active:true,phone:b.phone||'',dailyPay:50,wallet:0,upi:'',photo:b.photo||null,createdAt:iso()};d.users.push(x);note(d,x.id,'Welcome to ISC','Your team account was created by Admin.');act(d,'admin','TEAM_CREATED',x.name);save(d);return send(res,200,{user:safeUser(x)})}
if(req.method==='POST'&&p==='/api/team/update'){const b=await body(req),x=d.users.find(x=>x.id===b.id);if(!x)return send(res,404,{error:'Member not found'});Object.assign(x,{name:b.name??x.name,phone:b.phone??x.phone,active:b.active!==undefined?!!b.active:x.active,dailyPay:50});if(b.password)x.password=b.password;if(b.photo!==undefined)x.photo=b.photo;save(d);return send(res,200,{user:safeUser(x)})}
if(req.method==='POST'&&p==='/api/profile'){const b=await body(req),x=d.users.find(x=>x.id===b.userId);if(!x)return send(res,404,{error:'User not found'});x.phone=b.phone??x.phone;x.upi=b.upi??x.upi;if(b.photo!==undefined)x.photo=b.photo;save(d);return send(res,200,{user:safeUser(x)})}
if(req.method==='POST'&&p==='/api/proximity/admin'){const b=await body(req),x=d.users.find(u=>u.id===b.userId);if(!x||x.role!=='admin')return send(res,403,{error:'Admin transmitter access required'});if(typeof b.lat!=='number'||typeof b.lon!=='number')return send(res,400,{error:'Admin location required'});d.proximity.admin={lat:b.lat,lon:b.lon,accuracy:Number(b.accuracy||0),updatedAt:Date.now()};save(d);return send(res,200,{ok:true,transmitter:d.proximity.admin,radiusM:50})}
if(req.method==='POST'&&p==='/api/proximity/team'){const b=await body(req),x=d.users.find(u=>u.id===b.userId);if(!x||x.role!=='member')return send(res,403,{error:'Team receiver access required'});if(typeof b.lat!=='number'||typeof b.lon!=='number')return send(res,400,{error:'Team location required'});d.proximity.teams[x.id]={lat:b.lat,lon:b.lon,accuracy:Number(b.accuracy||0),updatedAt:Date.now()};const a=d.proximity.admin,dist=a?distanceM(a.lat,a.lon,b.lat,b.lon):null;save(d);return send(res,200,{active:!!(a&&Date.now()-a.updatedAt<=10000&&dist!==null&&dist<=50),distance:dist,thresholdM:50,transmitterOnline:!!(a&&Date.now()-a.updatedAt<=10000)})}
if(req.method==='GET'&&p==='/api/proximity/status'){const uid=u.searchParams.get('userId'),x=d.users.find(z=>z.id===uid);if(!x)return send(res,404,{error:'User not found'});const a=d.proximity.admin,tm=d.proximity.teams[uid],online=!!(a&&Date.now()-a.updatedAt<=10000),dist=a&&tm?distanceM(a.lat,a.lon,tm.lat,tm.lon):null;return send(res,200,{transmitterOnline:online,receiverOnline:!!(tm&&Date.now()-tm.updatedAt<=10000),distance:dist,within50m:!!(online&&tm&&dist<=50),thresholdM:50})}
if(req.method==='POST'&&p==='/api/proximity/scan'){const b=await body(req),x=d.users.find(x=>x.id===b.userId),a=d.proximity&&d.proximity.admin;if(!x)return send(res,404,{error:'User not found'});if(!a||Date.now()-a.updatedAt>10000)return send(res,200,{inside:false,distance:null,reason:'ISC Admin transmitter is offline. Keep the Admin Office page active.'});const lat=Number(b.lat),lon=Number(b.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))return send(res,400,{error:'Valid location is required'});const dist=distanceM(lat,lon,a.lat,a.lon);if(dist>50)return send(res,200,{inside:false,distance:dist,reason:`OUT OF OFFICE LOCATION · ${dist.toFixed(1)}m away · maximum 50m`});return send(res,200,{inside:true,distance:dist,reason:'ISC OFFICE FOUND'});}
if(req.method==='POST'&&p==='/api/attendance'){const b=await body(req),x=d.users.find(x=>x.id===b.userId);if(!x)return send(res,404,{error:'User not found'});const day=b.date||today(),existing=d.attendance.find(a=>a.userId===x.id&&a.date===day),t=iso();if(b.kind==='proximity_checkin'){const a=d.proximity.admin,tm=d.proximity.teams[x.id],online=!!(a&&Date.now()-a.updatedAt<=10000),dist=a&&tm?distanceM(a.lat,a.lon,tm.lat,tm.lon):null;if(!online||dist===null||dist>50)return send(res,403,{error:online?`Outside Admin transmitter range. Team device is ${dist.toFixed(1)}m away; maximum is 50m.`:'Admin transmitter is offline. Keep the Admin Office page active.',distance:dist});if(existing?.checkin)return send(res,200,{attendance:existing,distance:dist,already:true});const rec=existing||{id:id('att'),userId:x.id,date:day,checkin:null,checkout:null,photo:null,earned:0};rec.checkin=t;rec.checkinMode='ADMIN_TRANSMITTER';rec.checkinDistance=Number(dist.toFixed(2));rec.transmitterLat=a.lat;rec.transmitterLon=a.lon;if(!existing)d.attendance.push(rec);note(d,x.id,'Attendance recorded','Automatic proximity check-in accepted within 50m of the ISC Admin transmitter.','success');act(d,x.id,'PROXIMITY_CHECK_IN',day+' | '+dist.toFixed(2)+'m');save(d);return send(res,200,{attendance:rec,distance:dist})}if(b.kind==='checkout'){if(!existing?.checkin)return send(res,400,{error:'Check in first'});if(existing.checkout)return send(res,400,{error:'Attendance already checked out today'});const workedHours=(new Date(t).getTime()-new Date(existing.checkin).getTime())/3600000;if(workedHours<5)return send(res,400,{error:`Minimum 5 hours required before check-out. Only ${workedHours.toFixed(1)} hours completed.`});existing.checkout=t;existing.earned=50;if(Number(d.settings.adminWallet)<50)return send(res,400,{error:'Admin wallet has insufficient funds for ₹50 attendance payment'});d.settings.adminWallet-=50;x.wallet=Number(x.wallet||0)+50;tx(d,x.id,'EARNING',50,'Daily attendance earning',{date:day,source:'admin_wallet'});tx(d,'admin','ATTENDANCE_PAYMENT',-50,'Daily attendance payment to '+x.name,{date:day,memberId:x.id});note(d,x.id,'₹50 added','₹50 was added to your team wallet for today.','success');note(d,'admin','Attendance payment',x.name+' received ₹50 for '+day+'.');act(d,x.id,'CHECK_OUT',day+' | ₹50');save(d);return send(res,200,{attendance:existing,wallet:x.wallet})}return send(res,400,{error:'Manual GPS attendance is disabled. Use the ISC Admin transmitter proximity attendance.'})}
if(req.method==='POST'&&p==='/api/video'){const b=await body(req);if(!b.title||!Array.isArray(b.memberIds)||!b.memberIds.length)return send(res,400,{error:'Title and at least one team member required'});const v={id:id('v'),title:b.title,date:b.date||'',start:b.start||'',end:b.end||'',location:b.location||'',notes:b.notes||'',memberIds:b.memberIds,status:'Scheduled',createdAt:iso()};d.videos.unshift(v);v.memberIds.forEach(mid=>note(d,mid,'New video schedule',v.title+' • '+v.date+' '+v.start));save(d);return send(res,200,{video:v})}
if(req.method==='POST'&&p==='/api/video/status'){const b=await body(req),v=d.videos.find(x=>x.id===b.id);if(!v)return send(res,404,{error:'Video not found'});v.status=b.status;save(d);return send(res,200,{video:v})}
if(req.method==='GET'&&p==='/api/meeting/get'){const mid=u.searchParams.get('meetingId'),uid=u.searchParams.get('userId'),m=meetingFor(d,mid);if(!m||!meetingMember(d,m,uid))return send(res,403,{error:'Meeting access denied'});return send(res,200,{meeting:m,serverTime:Date.now()})}
if(req.method==='GET'&&p==='/api/meeting/signals'){const mid=u.searchParams.get('meetingId'),uid=u.searchParams.get('userId'),after=Number(u.searchParams.get('after')||0),m=meetingFor(d,mid);if(!m||!meetingMember(d,m,uid))return send(res,403,{error:'Meeting access denied'});const signals=(d.meetingSignals||[]).filter(x=>x.meetingId===mid&&x.from!==uid&&x.createdAt>after&&(x.to===null||x.to===uid)).slice(-100);return send(res,200,{signals,serverTime:Date.now()})}
if(req.method==='POST'&&p==='/api/meeting/signal'){const b=await body(req),m=meetingFor(d,b.meetingId);if(!m||!meetingMember(d,m,b.from))return send(res,403,{error:'Meeting access denied'});meetingSignal(d,b.meetingId,b.from,b.to||null,b.type,b.payload);save(d);return send(res,200,{ok:true})}
if(req.method==='POST'&&p==='/api/meeting/end'){const b=await body(req),m=meetingFor(d,b.meetingId);if(!m||b.userId!=='admin')return send(res,403,{error:'Only Admin can end the meeting'});m.status='Ended';m.endedAt=iso();save(d);return send(res,200,{meeting:m})}
if(req.method==='GET'&&p==='/api/meeting/export'){const mid=u.searchParams.get('meetingId'),uid=u.searchParams.get('userId'),m=meetingFor(d,mid);if(!m||uid!=='admin')return send(res,403,{error:'Admin access required'});const lines=['ISC OFFICE MEETING','Title: '+m.title,'Date: '+m.date,'Time: '+m.time,'Agenda: '+m.agenda,'Created: '+m.createdAt,'Status: '+(m.status||'Scheduled'),'Live link: /meeting.html?id='+m.id,'Members: '+m.memberIds.join(', ')];res.writeHead(200,{'Content-Type':'text/plain; charset=utf-8','Content-Disposition':'attachment; filename="ISC-meeting-'+m.id+'.txt"'});return res.end(lines.join('\n'))}
if(req.method==='POST'&&p==='/api/meeting'){const b=await body(req);if(!b.title||!b.memberIds?.length)return send(res,400,{error:'Meeting title and members required'});const m={id:id('m'),title:b.title,date:b.date||'',time:b.time||'',agenda:b.agenda||'',memberIds:b.memberIds,link:'/meeting.html?id='+encodeURIComponent(id('m')),status:'Scheduled',createdAt:iso()};m.link='/meeting.html?id='+encodeURIComponent(m.id);d.meetings.unshift(m);m.memberIds.forEach(mid=>note(d,mid,'Meeting scheduled',m.title+' • '+m.date+' '+m.time));save(d);return send(res,200,{meeting:m})}
if(req.method==='POST'&&p==='/api/voucher'){const b=await body(req),x=d.users.find(x=>x.id===b.userId);if(!x)return send(res,404,{error:'User not found'});if(!['Jio','Airtel','Vi','BSNL'].includes(b.operator))return send(res,400,{error:'Select a valid operator'});if(!/^[0-9]{10}$/.test(b.number))return send(res,400,{error:'Enter a valid 10-digit mobile number'});const amount=Number(b.amount);if(!amount||amount<10)return send(res,400,{error:'Enter a valid recharge amount'});const v={id:id('r'),userId:x.id,memberName:x.name,operator:b.operator,number:b.number,name:b.name||x.name,amount,status:'Pending',createdAt:iso(),paidAt:null};d.vouchers.unshift(v);note(d,'admin','Recharge request',x.name+' requested ₹'+amount+' '+b.operator+' recharge.','warning');note(d,x.id,'Recharge request submitted','Admin wallet will fund the recharge escrow when Admin processes it. Your team wallet remains separate from recharge settlement.');save(d);return send(res,200,{voucher:v,wallet:x.wallet})}
if(req.method==='POST'&&p==='/api/voucher/action'){const b=await body(req),v=d.vouchers.find(x=>x.id===b.id);if(!v)return send(res,404,{error:'Request not found'});if(v.status!=='Pending')return send(res,400,{error:'Request already processed'});const member=d.users.find(x=>x.id===v.userId);if(!member)return send(res,404,{error:'Member not found'});if(b.action==='approve'){if(!settleRechargeFromAdmin(d,member,v))return send(res,400,{error:'Admin wallet has insufficient funds for this recharge. Add sufficient Admin funds first.'});save(d);return send(res,200,{voucher:v,adminWallet:d.settings.adminWallet,teamWallet:member.wallet})}v.status='Rejected';v.rejectedAt=iso();note(d,v.userId,'Recharge rejected','Admin rejected your ₹'+v.amount+' recharge request.','error');act(d,'admin','RECHARGE_REJECTED',v.memberName+' ₹'+v.amount);save(d);return send(res,200,{voucher:v,adminWallet:d.settings.adminWallet})}
if(req.method==='POST'&&p==='/api/admin-wallet'){const b=await body(req),n=Number(b.amount);if(!n||n<=0)return send(res,400,{error:'Enter a valid amount'});d.settings.adminWallet+=n;tx(d,'admin','WALLET_TOPUP',n,'Admin wallet funds added',{balance:d.settings.adminWallet});act(d,'admin','WALLET_TOPUP','₹'+n);processPendingRecharges(d);save(d);return send(res,200,{balance:d.settings.adminWallet})}
if(req.method==='POST'&&p==='/api/admin-wallet/set'){const b=await body(req),n=Number(b.amount);if(!Number.isFinite(n)||n<0)return send(res,400,{error:'Enter a valid Admin wallet balance'});const old=Number(d.settings.adminWallet||0);d.settings.adminWallet=n;tx(d,'admin','WALLET_ADJUST',n-old,'Admin wallet balance adjusted',{previous:old,current:n});act(d,'admin','WALLET_ADJUST',money(old)+' → '+money(n));processPendingRecharges(d);save(d);return send(res,200,{balance:d.settings.adminWallet})}
if(req.method==='POST'&&p==='/api/withdraw'){const b=await body(req),x=d.users.find(x=>x.id===b.userId);if(!x)return send(res,404,{error:'User not found'});const n=Number(b.amount);if(!n||n<=0||n>x.wallet)return send(res,400,{error:'Invalid withdrawal amount or insufficient wallet'});if(!x.upi&&!b.upi)return send(res,400,{error:'Add your UPI ID first'});if(b.upi)x.upi=b.upi;const w={id:id('w'),userId:x.id,memberName:x.name,amount:n,upi:x.upi,status:'Pending',createdAt:iso(),paidAt:null};d.withdrawals.unshift(w);note(d,'admin','Salary withdrawal request',x.name+' requested '+money(n)+' to '+x.upi,'warning');note(d,x.id,'Withdrawal submitted','Your withdrawal request is waiting for Admin payment.');save(d);return send(res,200,{withdrawal:w})}
if(req.method==='POST'&&p==='/api/withdraw/action'){const b=await body(req),w=d.withdrawals.find(x=>x.id===b.id),x=w&&d.users.find(x=>x.id===w.userId);if(!w||!x)return send(res,404,{error:'Withdrawal not found'});if(w.status!=='Pending')return send(res,400,{error:'Withdrawal already processed'});if(b.action==='approve'){if(d.settings.adminWallet<w.amount||x.wallet<w.amount)return send(res,400,{error:'Admin or member wallet balance is insufficient'});d.settings.adminWallet-=w.amount;x.wallet-=w.amount;w.status='Paid';w.paidAt=iso();tx(d,'admin','SALARY_PAYOUT',-w.amount,'Salary payout to member',{memberId:x.id,withdrawalId:w.id,upi:w.upi});tx(d,x.id,'WITHDRAWAL',-w.amount,'Salary payout sent to UPI',{withdrawalId:w.id,upi:w.upi});note(d,x.id,'Salary paid',money(w.amount)+' salary marked paid to '+w.upi,'success')}else{w.status='Rejected';note(d,x.id,'Withdrawal rejected','Admin rejected your salary withdrawal request.','error')}save(d);return send(res,200,{withdrawal:w,adminWallet:d.settings.adminWallet})}
if(req.method==='POST'&&p==='/api/notification/read'){const b=await body(req);d.notifications.filter(n=>n.userId===b.userId).forEach(n=>n.read=true);d.notificationHistory.filter(n=>n.userId===b.userId).forEach(n=>n.read=true);save(d);return send(res,200,{ok:true})}
send(res,404,{error:'API route not found'})}
async function handler(req,res){try{if(req.url.startsWith('/api/'))return await api(req,res);const p=new URL(req.url,'http://localhost').pathname;if(p==='/'||p==='/index.html')return html(res,'index.html');return html(res,p.slice(1))}catch(e){console.error(e);send(res,500,{error:e.message})}}
module.exports=handler;
if(require.main===module){
  const server=http.createServer(handler);
  server.listen(process.env.PORT||3000,()=>console.log('ISC OFFICE running on http://localhost:'+(process.env.PORT||3000)));
}
